### ISSUE TITLE
CampJS SydJS Roadtrip Interest

### ISSUE THREAD

**Issue by DamonOehlman** [DamonOehlman/campjs-sydjs-roadtrip#1]
If you are interested in getting in on this whole road trip thing, then register your interest here.  We'll get down to more concrete coordination as we go along.

If you've visited this page from the tiny.cc short url - then feel free to checkout the [README](https://github.com/DamonOehlman/campjs-sydjs-roadtrip) on some thoughts I have put together so far.

**REMINDER**: If you do not yet have a CampJS ticket and attend SydJS then can get a ticket for $350 using the following discount link:

https://ti.to/campjs/campjs-v/with/nlt7fhrw3yo

_that is until they run out..._

**Comment by freshtonic** [comment]
Count me in :+1:

**Comment by JedWatson** [comment]
Me too, obviously :smile:

**Comment by JedWatson** [comment]
ping @cgiffard

**Comment by cgiffard** [comment]
+1

**Comment by leijing7** [comment]
One more in.
I was looking for this for a while.

**Comment by freshtonic** [comment]
I've already mentioned to @DamonOehlman, but I can no longer make it to CampJS. Also, if you know anyone that would like a ticket...

**Comment by ButenkoT** [comment]
Im in
