### ISSUE TITLE
Locking down final details

### ISSUE THREAD

**Issue by DamonOehlman** [DamonOehlman/campjs-sydjs-roadtrip#3]
It's only three more days before we all hit the road so I thought it was probably time to try and lock down final details.  Let's start with where people are roughly located, and we can start to determine whether we manage fairly adhoc departure from Sydney meeting up somewhere on the way to Melbourne.

In the case that we are all spread out over the city (which is likely) I'd suggest coordinating somewhere that is in Sydney (roughly) with good rail access before heading out.

@JedWatson @cgiffard @leijing7

**Comment by DamonOehlman** [comment]
BTW, I'm in Engadine (which is South).

**Comment by JedWatson** [comment]
I'm in Willoughby, most Thinkmill are going to meet up in our office in the CBD.

**Comment by JedWatson** [comment]
@cgiffard can stop by your place if you like and pick you up before I cross the bridge

**Comment by DamonOehlman** [comment]
@JedWatson thought that might be the case, so really it's just a matter of me picking up @leijing7 from somewhere and us coordinating somewhere south of the city.  What time are you aiming to leave the Thinkmill office?

Was there anyone I missed who had expressed interest on #1?

**Comment by leijing7** [comment]
I live in Revesby. I can drive to a meet place as long as I can park my car or take train.

**Comment by DamonOehlman** [comment]
@leijing7 That's close enough to me that we can work something out.  Email me (damon.oehlman -at- gmail.com) your address and I'll work out how enroute picking you up would be for me.

**Comment by leijing7** [comment]
@DamonOehlman emailed you my address. Thanks for organising it.
